<a href="https://colab.research.google.com/github/2303A51923/PDS/blob/main/Lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print("2D Array A (shape:", A.shape, "):\n", A)
print("1D Array B (shape:", B.shape, "):\n", B)

C = A + B
print("\nResult of A + B (shape:", C.shape, "):\n", C)

D = np.ones((2,3,4))
scalar = 5

print("\n3D Array D (shape:", D.shape, ")\n", D)
print("Scalar value:", scalar)

E = D + scalar
print("\nResult of D + scalar (shape:", E.shape, "):\n", E)
F = np.array([1, 2, 3])
G = np.array([10, 20])

print("\nArray F (shape:", F.shape, "):", F)
print("Array G (shape:", G.shape, "):", G)

F_new = F[np.newaxis, :]
G_new = G[:, np.newaxis]

print("\nF reshaped (1,3):\n", F_new)
print("G reshaped (2,1):\n", G_new)

H = F_new + G_new
print("\nResult of F_new + G_new (shape:", H.shape, "):\n", H)
I = np.array([1, 2, 3])
J = np.array([10, 20, 30, 40])

print("\nInvalid Broadcasting Example:")
print("I shape:", I.shape, " J shape:", J.shape)

try:
    K = I + J
except ValueError as e:
    print("❌ Broadcasting Error:", e)


2D Array A (shape: (2, 3) ):
 [[1 2 3]
 [4 5 6]]
1D Array B (shape: (3,) ):
 [10 20 30]

Result of A + B (shape: (2, 3) ):
 [[11 22 33]
 [14 25 36]]

3D Array D (shape: (2, 3, 4) )
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Scalar value: 5

Result of D + scalar (shape: (2, 3, 4) ):
 [[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]

Array F (shape: (3,) ): [1 2 3]
Array G (shape: (2,) ): [10 20]

F reshaped (1,3):
 [[1 2 3]]
G reshaped (2,1):
 [[10]
 [20]]

Result of F_new + G_new (shape: (2, 3) ):
 [[11 12 13]
 [21 22 23]]

Invalid Broadcasting Example:
I shape: (3,)  J shape: (4,)
❌ Broadcasting Error: operands could not be broadcast together with shapes (3,) (4,) 


In [2]:
import numpy as np
A = np.array([[4, -9, 16],
              [25, -36, 49],
              [64, -1, 100]])

print("Original 2D Array (shape:", A.shape, "):\n", A)
A_squared = np.square(A)
print("\nSquared Array:\n", A_squared)
A_sqrt = np.sqrt(np.abs(A))
print("\nSquare Root of Absolute Values:\n", A_sqrt)
A_non_negative = np.where(A < 0, 0, A)
print("\nArray with Negatives Replaced by Zero:\n", A_non_negative)
count_gt_10 = np.sum(A_non_negative > 10)
print("\nNumber of elements > 10:", count_gt_10)
mask_gt_10 = A_non_negative > 10
print("\nMask Matrix (True where value > 10):\n", mask_gt_10)
values_gt_10 = A_non_negative[mask_gt_10]
print("\nValues > 10:", values_gt_10)
print("\n--- Summary of Steps ---")
print("1. Started with a 2D integer array (with negatives).")
print("2. Squared all elements (element-wise).")
print("3. Took square root of absolute values.")
print("4. Replaced negatives with 0 using np.where().")
print("5. Counted elements > 10:", count_gt_10)
print("6. Created a mask matrix to visualize condition results.")


Original 2D Array (shape: (3, 3) ):
 [[  4  -9  16]
 [ 25 -36  49]
 [ 64  -1 100]]

Squared Array:
 [[   16    81   256]
 [  625  1296  2401]
 [ 4096     1 10000]]

Square Root of Absolute Values:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  1. 10.]]

Array with Negatives Replaced by Zero:
 [[  4   0  16]
 [ 25   0  49]
 [ 64   0 100]]

Number of elements > 10: 5

Mask Matrix (True where value > 10):
 [[False False  True]
 [ True False  True]
 [ True False  True]]

Values > 10: [ 16  25  49  64 100]

--- Summary of Steps ---
1. Started with a 2D integer array (with negatives).
2. Squared all elements (element-wise).
3. Took square root of absolute values.
4. Replaced negatives with 0 using np.where().
5. Counted elements > 10: 5
6. Created a mask matrix to visualize condition results.
